// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkpeC3nD9juS7gHG4qHE4dk1IWRGQXwKk',
    appId: '1:1070210806389:web:ea6bcceff0e115bbcb3e3c',
    messagingSenderId: '1070210806389',
    projectId: 'playspot-83bcb',
    authDomain: 'playspot-83bcb.firebaseapp.com',
    storageBucket: 'playspot-83bcb.firebasestorage.app',
    measurementId: 'G-NC32H9JT4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmM1rXwj252NZL-ff1lNz-PuvZu1h7MeM',
    appId: '1:1070210806389:android:d7d5a3b1db6f74cecb3e3c',
    messagingSenderId: '1070210806389',
    projectId: 'playspot-83bcb',
    storageBucket: 'playspot-83bcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAI6pa5w7lU45szgzPrSLNJuJEED70AKo',
    appId: '1:1070210806389:ios:c296b2e59d3ebf87cb3e3c',
    messagingSenderId: '1070210806389',
    projectId: 'playspot-83bcb',
    storageBucket: 'playspot-83bcb.firebasestorage.app',
    iosClientId: '1070210806389-juipdsj2bbvqotrue4fc9nnqf36plhrt.apps.googleusercontent.com',
    iosBundleId: 'com.example.playspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAI6pa5w7lU45szgzPrSLNJuJEED70AKo',
    appId: '1:1070210806389:ios:c296b2e59d3ebf87cb3e3c',
    messagingSenderId: '1070210806389',
    projectId: 'playspot-83bcb',
    storageBucket: 'playspot-83bcb.firebasestorage.app',
    iosClientId: '1070210806389-juipdsj2bbvqotrue4fc9nnqf36plhrt.apps.googleusercontent.com',
    iosBundleId: 'com.example.playspot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkpeC3nD9juS7gHG4qHE4dk1IWRGQXwKk',
    appId: '1:1070210806389:web:ae2f4216eff37d37cb3e3c',
    messagingSenderId: '1070210806389',
    projectId: 'playspot-83bcb',
    authDomain: 'playspot-83bcb.firebaseapp.com',
    storageBucket: 'playspot-83bcb.firebasestorage.app',
    measurementId: 'G-RXX66W3XWR',
  );
}
